// Generated by CoffeeScript 1.6.2
(function(window, document) {
  var currentOrientation, debounce, dispatchResizeEndEvent, event, getCurrentOrientation, initialOrientation, resizeDebounceTimeout;

  if (!(window.addEventListener && document.createEvent)) {
    return;
  }
  event = null;
  dispatchResizeEndEvent = function() {
    if (!event) {
      event = document.createEvent('Event');
      event.initEvent('resizeend', false, false);
    }
    return window.dispatchEvent(event);
  };
  getCurrentOrientation = function() {
    return Math.abs(+window.orientation || 0) % 180;
  };
  initialOrientation = getCurrentOrientation();
  currentOrientation = null;
  resizeDebounceTimeout = null;
  debounce = function() {
    currentOrientation = getCurrentOrientation();
    if (currentOrientation !== initialOrientation) {
      dispatchResizeEndEvent();
      return initialOrientation = currentOrientation;
    } else {
      clearTimeout(resizeDebounceTimeout);
      return resizeDebounceTimeout = setTimeout(dispatchResizeEndEvent, 100);
    }
  };
  return window.addEventListener('resize', debounce, false);
})(window, document);
